In [2]:
import pandas as pd

# Lee el archivo CSV en un DataFrame de pandas
df = pd.read_csv('Bueno_Final.csv', sep = ';')

# Muestra las primeras filas del DataFrame
df

nombres_variables = df.columns
print(nombres_variables)

Index(['Date_Create', 'IP_Adress', 'Operador', 'Auxiliar', 'Jefe_de_dia',
       'Fecha_intervencion', 'Fecha_Nacimiento', 'Genero',
       'Patologia_1stemica', 'Medicacion_actual',
       ...
       'Amoxicilina 500 mg', 'Amoxicilina/Ácido Clavulánico 1000/125 mg',
       'Metronidazol 250 mg', 'Ibuprofeno 400 mg', 'Ibuprofeno 20 mg/ml',
       'Dexketoprofeno 25 mg', 'Diclofenaco 50 mg', 'Paracetamol 500 mg',
       'Paracetamol 100 mg/ml', 'Otro (especifique)_625'],
      dtype='object', length=928)

/var/folders/st/jjkf9ymj499b718tlxyzmp380000gn/T/ipykernel_3192/4186036420.py:4: DtypeWarning: Columns (110,227,237,756,757,790,793,927) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Bueno_Final.csv', sep = ';')

In [13]:
df = df.replace(0, pd.NA)
df

df = df.fillna(0)
df

,Date_Create,IP_Adress,Operador,Auxiliar,Jefe_de_dia,Fecha_intervencion,Fecha_Nacimiento,Genero,Patologia_1stemica,Medicacion_actual,...,Amoxicilina 500 mg,Amoxicilina/Ácido Clavulánico 1000/125 mg,Metronidazol 250 mg,Ibuprofeno 400 mg,Ibuprofeno 20 mg/ml,Dexketoprofeno 25 mg,Diclofenaco 50 mg,Paracetamol 500 mg,Paracetamol 100 mg/ml,Otro (especifique)_625
0,11/03/2019 08:52:38 PM,7.914477e+08,8.0,8.0,11.0,30/10/19,8/3/71,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,11/03/2019 08:51:09 PM,7.914477e+08,8.0,8.0,8.0,22/10/19,3/6/93,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,11/03/2019 08:48:12 PM,7.914477e+08,8.0,9.0,10.0,18/10/19,10/10/95,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,11/03/2019 08:45:31 PM,7.914477e+08,8.0,5.0,9.0,18/10/19,26/3/96,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,11/03/2019 08:42:13 PM,7.914477e+08,8.0,14.0,9.0,18/10/19,2/7/83,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105,11/22/2016 07:30:13 PM,8.118415e+10,7.0,12.0,5.0,3/11/16,21/6/70,Mujer,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2106,0,0.000000e+00,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2107,0,0.000000e+00,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2108,0,0.000000e+00,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2109,0,0.000000e+00,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [14]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df y una lista de rangos de columnas seleccionadas
column_ranges = [(0, 928)]  # Ejemplo de rangos de columnas seleccionadas

# Función para transformar los valores numéricos a 1
def transform_values(x):
    if isinstance(x, (int, float)) and x != 0:  # Verifica si x es un número y no es 0
        return 1
    else:
        return x

# Aplicar la función a las columnas seleccionadas del DataFrame
for start, end in column_ranges:
    df.iloc[:, start:end+1] = df.iloc[:, start:end+1].applymap(transform_values)

    
df

,Date_Create,IP_Adress,Operador,Auxiliar,Jefe_de_dia,Fecha_intervencion,Fecha_Nacimiento,Genero,Patologia_1stemica,Medicacion_actual,...,Amoxicilina 500 mg,Amoxicilina/Ácido Clavulánico 1000/125 mg,Metronidazol 250 mg,Ibuprofeno 400 mg,Ibuprofeno 20 mg/ml,Dexketoprofeno 25 mg,Diclofenaco 50 mg,Paracetamol 500 mg,Paracetamol 100 mg/ml,Otro (especifique)_625
0,11/03/2019 08:52:38 PM,1.0,1.0,1.0,1.0,30/10/19,8/3/71,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,11/03/2019 08:51:09 PM,1.0,1.0,1.0,1.0,22/10/19,3/6/93,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,11/03/2019 08:48:12 PM,1.0,1.0,1.0,1.0,18/10/19,10/10/95,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,11/03/2019 08:45:31 PM,1.0,1.0,1.0,1.0,18/10/19,26/3/96,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,11/03/2019 08:42:13 PM,1.0,1.0,1.0,1.0,18/10/19,2/7/83,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105,11/22/2016 07:30:13 PM,1.0,1.0,1.0,1.0,3/11/16,21/6/70,Mujer,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2106,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2107,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2108,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2109,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [15]:
# Exportar el DataFrame a un archivo CSV
df.to_csv('combianted_Total.csv', index=False)
df

,Date_Create,IP_Adress,Operador,Auxiliar,Jefe_de_dia,Fecha_intervencion,Fecha_Nacimiento,Genero,Patologia_1stemica,Medicacion_actual,...,Amoxicilina 500 mg,Amoxicilina/Ácido Clavulánico 1000/125 mg,Metronidazol 250 mg,Ibuprofeno 400 mg,Ibuprofeno 20 mg/ml,Dexketoprofeno 25 mg,Diclofenaco 50 mg,Paracetamol 500 mg,Paracetamol 100 mg/ml,Otro (especifique)_625
0,11/03/2019 08:52:38 PM,1.0,1.0,1.0,1.0,30/10/19,8/3/71,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,11/03/2019 08:51:09 PM,1.0,1.0,1.0,1.0,22/10/19,3/6/93,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,11/03/2019 08:48:12 PM,1.0,1.0,1.0,1.0,18/10/19,10/10/95,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,11/03/2019 08:45:31 PM,1.0,1.0,1.0,1.0,18/10/19,26/3/96,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,11/03/2019 08:42:13 PM,1.0,1.0,1.0,1.0,18/10/19,2/7/83,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105,11/22/2016 07:30:13 PM,1.0,1.0,1.0,1.0,3/11/16,21/6/70,Mujer,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2106,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2107,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2108,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2109,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [19]:
df1 = pd.read_csv('combined_dataframe_final.csv')
df1['Número_de_cigarrillos.día']

/var/folders/st/jjkf9ymj499b718tlxyzmp380000gn/T/ipykernel_26583/3345650380.py:1: DtypeWarning: Columns (235,245,248,764,765,798,801,935) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('combined_dataframe_final.csv')

0        0
1        0
2        0
3        0
4        0
        ..
2101     0
2102     0
2103     0
2104    10
2105     6
Name: Número_de_cigarrillos.día, Length: 2106, dtype: int64

In [24]:
# Union

df['Cigarros Diarios'] = df1['Número_de_cigarrillos.día']
df['ID_Paciente'] = df1['responded_ID']
df

,Date_Create,IP_Adress,Operador,Auxiliar,Jefe_de_dia,Fecha_intervencion,Fecha_Nacimiento,Genero,Patologia_1stemica,Medicacion_actual,...,Metronidazol 250 mg,Ibuprofeno 400 mg,Ibuprofeno 20 mg/ml,Dexketoprofeno 25 mg,Diclofenaco 50 mg,Paracetamol 500 mg,Paracetamol 100 mg/ml,Otro (especifique)_625,Cigarros Diarios,ID_Paciente
0,11/03/2019 08:52:38 PM,1.0,1.0,1.0,1.0,30/10/19,8/3/71,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111395e+10
1,11/03/2019 08:51:09 PM,1.0,1.0,1.0,1.0,22/10/19,3/6/93,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111395e+10
2,11/03/2019 08:48:12 PM,1.0,1.0,1.0,1.0,18/10/19,10/10/95,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111394e+10
3,11/03/2019 08:45:31 PM,1.0,1.0,1.0,1.0,18/10/19,26/3/96,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111394e+10
4,11/03/2019 08:42:13 PM,1.0,1.0,1.0,1.0,18/10/19,2/7/83,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111394e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105,11/22/2016 07:30:13 PM,1.0,1.0,1.0,1.0,3/11/16,21/6/70,Mujer,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,6.0,5.108221e+09
2106,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN
2107,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN
2108,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN
2109,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN

In [26]:
# Exportar el DataFrame a un archivo CSV
df.to_csv('combianted_Total_P.csv', index=False)
df = df.iloc[:-4]
df

,Date_Create,IP_Adress,Operador,Auxiliar,Jefe_de_dia,Fecha_intervencion,Fecha_Nacimiento,Genero,Patologia_1stemica,Medicacion_actual,...,Metronidazol 250 mg,Ibuprofeno 400 mg,Ibuprofeno 20 mg/ml,Dexketoprofeno 25 mg,Diclofenaco 50 mg,Paracetamol 500 mg,Paracetamol 100 mg/ml,Otro (especifique)_625,Cigarros Diarios,ID_Paciente
0,11/03/2019 08:52:38 PM,1.0,1.0,1.0,1.0,30/10/19,8/3/71,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111395e+10
1,11/03/2019 08:51:09 PM,1.0,1.0,1.0,1.0,22/10/19,3/6/93,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111395e+10
2,11/03/2019 08:48:12 PM,1.0,1.0,1.0,1.0,18/10/19,10/10/95,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111394e+10
3,11/03/2019 08:45:31 PM,1.0,1.0,1.0,1.0,18/10/19,26/3/96,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111394e+10
4,11/03/2019 08:42:13 PM,1.0,1.0,1.0,1.0,18/10/19,2/7/83,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.111394e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2101,11/25/2016 08:06:42 PM,1.0,1.0,1.0,1.0,25/11/16,27/3/98,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,5.112253e+09
2102,11/24/2016 09:01:19 PM,1.0,1.0,1.0,1.0,14/11/16,30/1/97,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,5.111189e+09
2103,11/24/2016 08:55:22 PM,1.0,1.0,1.0,1.0,7/11/16,3/11/89,Hombre,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,5.111186e+09
2104,11/24/2016 06:58:49 PM,1.0,1.0,1.0,1.0,24/11/16,26/6/95,Mujer,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,10.0,5.111088e+09
2105,11/22/2016 07:30:13 PM,1.0,1.0,1.0,1.0,3/11/16,21/6/70,Mujer,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,6.0,5.108221e+09

In [4]:
df.to_csv('combianted_Total.csv', index=False)
df

nuevo_df2 = df.loc[:, ['Duracion']]  # Extraes las columnas 'A' y 'B' del DataFrame original
print(nuevo_df2)

KeyError: "None of [Index(['Duracion'], dtype='object')] are in the [columns]"